# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='title',
            new_name='story_title',
        ),
    ]
