# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 08:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20161113_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
