# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-09 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
